### ISSUE TITLE
nie moge zainstalowac doccli, mimo ze robie wszystko tak jak w instrukcji.

### ISSUE THREAD

**Issue by glodnyy** [TowarzyszFatCat/doccli#10]
```
xxx:~$ cd doccli
xxx:~/doccli$ sh install.sh
install.sh: 3: [: doccli: unexpected operator
WEJDZ DO FOLDERU DOCCLI!
xxx:~/doccli$ 

```
w xxx jest moja nazwa komputera

**Comment by TowarzyszFatCat** [comment]
Bardzo dziwny przypadek, jakiej dystrybucji używasz?

**Comment by glodnyy** [comment]
linux mint

**Comment by TowarzyszFatCat** [comment]
Zrobię live usb i postaram się oddtworzyć ten błąd. Dam znać jak dowiem się co jest nie tak.

**Comment by glodnyy** [comment]
Dobrze, dziękuje.

**Comment by TowarzyszFatCat** [comment]
- Na początku usuń folder doccli który wcześniej się pobrał np. `rm -rf doccli`
- Usuń pliki doccli które mogły się utworzyć: `sudo rm /usr/local/bin/doccli && sudo rm -rf ~/.doccli_src`
- Zainstaluj wymagane paczki: `sudo apt install mpv yt-dlp python3-venv` Na mincie domyślnie nie było paczki python3-venv
- Sklonuj repo: `git clone https://github.com/TowarzyszFatCat/doccli.git`
- Wejdź do folderu: `cd doccli`
- Zainstaluj komendą: `bash install.sh`

Wszystko powinno już działać. 
Pamiętaj też, że projekt jest ciągle w fazie rozwoju i jak narazie wspiera tylko cda i sibnet. 

Gdybyś spotkał się z błędem typu `Download Error` lub `Unable to download webpage` oznacza, że film został usunięty ze źródła i nic nie jestem w stanie z tym zrobić.

Każdy inny błąd możesz zgłaszać, bardzo mi to pomoże w dalszym rozwoju projektu.
Jeżeli wszystko będzie okej napisz mi to zamknę issue.

**Comment by glodnyy** [comment]
Tak!
Teraz już wszystko działa tak jak należy. Można już zamknąć to issue

Dzięki wielkie za pomoc, pozdrawiam!
