### ISSUE TITLE
Nie da sie zainstalować doccli po najnowszej aktualizacji

### ISSUE THREAD

**Issue by glodnyy** [TowarzyszFatCat/doccli#14]
Krotka historia: probowalem zaaktualizować doccli uzywajac komendy na glownej stronie repo, lecz po tym jak juz wszystkie procesy w terminalu wskazywały na ukonczenie aktualizacji sprobowalem wpisac doccli w terminal i nic sie nie wlaczylo i tylko taki error:   

```
File "/home/nazwa_uzytkownika/.doccli_src/run.py", line 21
    print(colored('Najnowsza wersja:', "white"), colored(f"{response.json()["name"]}", "green"))
                                                                                                                     ^^^^
SyntaxError: f-string: unmatched '['
```
Spróbowałem wten zainstalować odnowa. . Ale wynik był ten sam

**Dystrybucja: Linux Mint - Cinnamon**

**Comment by TowarzyszFatCat** [comment]
Zobacz teraz. Możesz użyć tej komendy żeby przeinstalować:
`sudo rm /usr/local/bin/doccli && sudo rm -rf ~/.doccli_src && cd ~ && git clone https://github.com/TowarzyszFatCat/doccli.git && bash doccli/install.sh`

**Comment by glodnyy** [comment]
Nie wiem jakim cudem, ale tak jak zawsze reinstalowalem musialem usunac folder doccli, wiec usunalem znow i zainstalowalem od nowa. I znów działa - a uzylem komendy ze strony, nie z issue. Tak więc problem rozwiązał sie sam - Podsumowując.
Reinstalowałem używając linków ze strony i zadziałało.
