### ISSUE TITLE
Błąd przy włączaniu doccli na macOS

### ISSUE THREAD

**Issue by Jckpt** [TowarzyszFatCat/doccli#15]
Po wybraniu anime na macOS dostaje błąd:

```bash
Traceback (most recent call last):
  File "/Users/jckpt/.doccli_src/run.py", line 33, in <module>
    m_welcome()
  File "/Users/jckpt/.doccli_src/main_module.py", line 96, in m_welcome
    w_players(continue_data[0]['slug'], continue_data[1])
  File "/Users/jckpt/.doccli_src/main_module.py", line 400, in w_players
    process = mpv_play(ans_index[1])
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jckpt/.doccli_src/main_module.py", line 450, in mpv_play
    process = Popen(args=['mpv' if platform.system() == "Linux" else WIN_mpv, "--save-position-on-quit", URL], shell=False, stdout=DEVNULL, stderr=DEVNULL)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jckpt/.config/doccli/essentials/mpv.com'
```

Zawartość folderu essentials:

```bash
jckpt@Macbook-jckpt doccli % ls
continue.json	history.json	mylist.json	settings.json
```

**Comment by TowarzyszFatCat** [comment]
Błąd wynika z pozostałości kodu do wsparcia doccli na windowsie, gdzie sprawdza czy używasz linuxa czy windowsa. W twoim przypadku jest to macOS więc program nie wie co ma ze sobą zrobić. :)
Postaram się to naprawić. (nigdy nie używałem macOS, więc trochę mi to zajmie) Nie wiedziałem nawet, że da radę odpalić doccli na macu, więc nie przewidziałem wsparcia.

**Comment by TowarzyszFatCat** [comment]
Ewentualnie możesz sprawdzić, czy program zadziała jak zamienisz 450 linijkę:
`process = Popen(args=['mpv' if platform.system() == "Linux" else WIN_mpv, "--save-position-on-quit", URL], shell=False, stdout=DEVNULL, stderr=DEVNULL)`
na
`process = Popen(args=["mpv", "--save-position-on-quit", URL], shell=False, stdout=DEVNULL, stderr=DEVNULL)`

Lokalizacja tego pliku: "/Users/jckpt/.doccli_src/main_module.py"
Pamiętaj żeby zostawić odstęp taki jaki jest (8 spacji)

**Comment by Jckpt** [comment]
udało mi się naprawić 
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/fec16fb6-7d2f-4c98-aef7-17fe3f3a6332">

**Comment by TowarzyszFatCat** [comment]
Dzięki wielkie, inaczej nie miał bym jak tego przetestować
